spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:mem:paymentsdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: '*'

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:web_hook_sec}
  base-url: ${BASE_URL:http://localhost:3000/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework: INFO
    com.sujit: DEBUG
